### ISSUE TITLE
date check failed

### ISSUE THREAD

**Issue by chaolinc** [srcagency/object-diff#5]
change the code to the following for the Date check to be working correctly.

if(c[key] instanceof Date){
                if(c[key].getTime() != ref[key].getTime())
                    diff[key] = c[key];
            } else {
                if (c[key] !== ref[key]){

```
                diff[key] = c[key];
            }
        }
```

**Comment by tjconcept** [comment]
Hi @chaolinc, thanks for filing an issue - but why did you close it again?

I am currently in the thinking about how and if this should be a part of this package, and whether it could be solved in a more generic way (`Date` is just one type of object).

**Comment by tangxinfa** [comment]
# Let the user to pass the compare function if required:

diff index.js index.new.js

```
5c5,16
< function diff(){
---
> 
> var default_options = {
>     equal: function (a, b) {
>         return a === b;
>     }
> };
> 
> function diff(options){
>     if (!options || !options.equal) {
>         options = default_options;
>     }
> 
23c34
<           if (c[key] !== ref[key])
---
>           if (! options.equal(c[key], ref[key]))
```

**Comment by tjconcept** [comment]
@tangxinfa nice approach. If you wanna cook up a PR, I'll be happy to include something like that.

For more future options, I'd prefer something like:
`var equal = options && options.equal || defaults.equal`

**Comment by tangxinfa** [comment]
@tjconcept 

I created PR(https://github.com/srcagency/object-diff/pull/6) by your advice, please have a look:)

**Comment by tjconcept** [comment]
Supported as of #6
