### ISSUE TITLE
Set removed attributes to undefined

### ISSUE THREAD

**Issue by Treora** [srcagency/object-diff#8]
Currently only additions and changes appear in the diff. I think it would be convenient and logical to treat removed attributes like attributes that were set to undefined. Possibly add a second loop roughly like this? (untested!)
```
var refKeys = Object.keys(ref);
var refKeysLength = refKeys.length;
var hasOwnProperty = Object.prototype.hasOwnProperty;
for (u = 0;u < refKeysLength;u++) {
	key = refKeys[u];
	if (!hasOwnProperty.call(c, key))
		diff[key] = undefined;
}
```

**Comment by pstanton** [comment]
agree, my initial read of the example on the home page left me asking "where is the 'removed' example?"

**Comment by tjconcept** [comment]
This package is generally meant to deal with data structures where the keys are not dynamic. For instance coordinates: `{x: 1, y: 4, x: 2}`.

I know that, by know, there are consumers relying on the feature that `diff(a, {})` will not produce a huge object but rather just `{}`.

For a more advanced diff'ing, I'd probably go with a completely different approach, such as compiling the list of keys initially (`keys = new Set(...Object.keys(a), ...Object.keys(b))`) and then calculate the diff based on that.

**Comment by pstanton** [comment]
so how do you detect key removal?

**Comment by tjconcept** [comment]
This package is not intended for scenarios where you'd be "removing" keys (and wish to track it). Generally (imo) there are very few legitimate scenarios where you should be "removing" keys. I, personally, don't use objects for maps.

Say you have a web form of "name" and "age":

```js
const before = {name: '', age: ''}
const after = {name: 'John', age: ''} // e.g. "onSubmit"
diff(before, after) //-> {name: 'John'}
```
